import type { WarmupConfigModel, Mailbox, WarmupJob } from '@/types/mail'

export function makeConfig(overrides: Partial<WarmupConfigModel> = {}): WarmupConfigModel {
  return {
    id: 'cfg-1',
    organizationId: 'org-1',
    mailboxId: 'mb-1',
    status: 'running',
    stage: 'initial',
    health: 'healthy',
    startDate: '2026-01-01T00:00:00Z',
    endDate: null,
    pausedAt: null,
    resumedAt: null,
    graduatedAt: null,
    currentDay: 5,
    totalDays: 30,
    initialSends: 5,
    maxDailySends: 50,
    dailyIncrease: 2,
    currentDailyTarget: 13,
    weekendSending: false,
    businessHoursStart: 9,
    businessHoursEnd: 17,
    timezone: 'UTC',
    minDelayMs: 30000,
    maxDelayMs: 120000,
    randomizationFactor: 0.3,
    replySimulation: true,
    readSimulation: true,
    spamRescue: true,
    openSimulation: true,
    clickSimulation: false,
    targetHealthScore: 80,
    graduationThreshold: 75,
    pauseThreshold: 30,
    resumeThreshold: 50,
    pauseReason: null,
    failureReason: null,
    metadata: {},
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    ...overrides,
  }
}

export function makeMailbox(overrides: Partial<Mailbox> = {}): Mailbox {
  return {
    id: 'mb-1',
    organizationId: 'org-1',
    poolId: null,
    provider: 'gmail',
    authType: 'oauth',
    email: 'test@example.com',
    displayName: 'Test',
    senderName: 'Test',
    providerAccountId: null,
    timezone: 'UTC',
    dailyLimit: 50,
    currentDailyUsage: 0,
    healthScore: 80,
    healthStatus: 'good',
    mailboxStatus: 'connected',
    verificationStatus: 'verified',
    warmupStatus: 'idle',
    lastVerifiedAt: null,
    lastVerificationDurationMs: null,
    lastVerificationResult: null,
    deletedAt: null,
    archivedAt: null,
    oauthConfig: null,
    smtpConfig: null,
    imapConfig: null,
    metadata: {},
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    ...overrides,
  }
}

export function makeJob(overrides: Partial<WarmupJob> = {}): WarmupJob {
  return {
    id: 'job-1',
    configId: 'cfg-1',
    organizationId: 'org-1',
    status: 'pending',
    scheduledAt: '2026-07-22T12:00:00Z',
    startedAt: null,
    completedAt: null,
    retryCount: 0,
    maxRetries: 3,
    nextRetryAt: null,
    lastError: null,
    errorCategory: null,
    targetSends: 13,
    completedSends: 0,
    failedSends: 0,
    mailboxId: 'mb-1',
    poolId: null,
    metadata: {},
    createdAt: '2026-07-22T12:00:00Z',
    updatedAt: '2026-07-22T12:00:00Z',
    ...overrides,
  }
}
